// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperedTyrant.CreatorToolkit.Infrastructure.Persistence;

#nullable disable

namespace TemperedTyrant.CreatorToolkit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CreatorToolkitDbContext))]
    [Migration("20260728192834_InitialIdentityAndSecurityFoundation")]
    partial class InitialIdentityAndSecurityFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetRoles_Name_Length", "\"Name\" IS NULL OR length(\"Name\") <= 256");

                            t.HasCheckConstraint("CK_AspNetRoles_NormalizedName_Length", "\"NormalizedName\" IS NULL OR length(\"NormalizedName\") <= 256");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0197fd3c-5a8d-7a20-b52b-5bd4a7dd7a01"),
                            ConcurrencyStamp = "owner",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("0197fd3c-5a8d-7a20-b52b-5bd4a7dd7a02"),
                            ConcurrencyStamp = "admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0197fd3c-5a8d-7a20-b52b-5bd4a7dd7a03"),
                            ConcurrencyStamp = "editor",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("0197fd3c-5a8d-7a20-b52b-5bd4a7dd7a04"),
                            ConcurrencyStamp = "viewer",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Audit.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticReference")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditRecords_DiagnosticReference_Length", "\"DiagnosticReference\" IS NULL\nOR length(\"DiagnosticReference\") BETWEEN 1 AND 64");

                            t.HasCheckConstraint("CK_AuditRecords_EventCode_Length", "length(\"EventCode\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_AuditRecords_Outcome_Length", "length(\"Outcome\") BETWEEN 1 AND 32");

                            t.HasCheckConstraint("CK_AuditRecords_ReasonCode_Length", "\"ReasonCode\" IS NULL OR length(\"ReasonCode\") BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Diagnostics.DiagnosticRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("DiagnosticRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiagnosticRecords_Category_Length", "length(\"Category\") BETWEEN 1 AND 64");

                            t.HasCheckConstraint("CK_DiagnosticRecords_ErrorCode_Length", "length(\"ErrorCode\") BETWEEN 1 AND 64");

                            t.HasCheckConstraint("CK_DiagnosticRecords_ExceptionType_Length", "\"ExceptionType\" IS NULL\nOR length(\"ExceptionType\") BETWEEN 1 AND 512");

                            t.HasCheckConstraint("CK_DiagnosticRecords_Operation_Length", "length(\"Operation\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_DiagnosticRecords_Reference_Length", "length(\"Reference\") BETWEEN 1 AND 64");

                            t.HasCheckConstraint("CK_DiagnosticRecords_Severity_Length", "length(\"Severity\") BETWEEN 1 AND 32");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Identity.Ownership", b =>
                {
                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TransferredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("Ownerships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ownerships_Revision", "Revision >= 0");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Setup.InstallationState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("InitializedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InstallationStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_InstallationStates_Revision", "Revision >= 0");

                            t.HasCheckConstraint("CK_InstallationStates_Singleton", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Revision = 0L
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Setup.SecurityCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSlot")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubjectUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Purpose", "ActiveSlot")
                        .IsUnique()
                        .HasFilter("\"ActiveSlot\" IS NOT NULL");

                    b.ToTable("SecurityCapabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_SecurityCapabilities_ActiveSlot_State", "\"ActiveSlot\" IS NULL\nOR (\n    length(\"ActiveSlot\") BETWEEN 1 AND 128\n    AND \"UsedAtUtc\" IS NULL\n    AND \"RevokedAtUtc\" IS NULL\n)");

                            t.HasCheckConstraint("CK_SecurityCapabilities_Lifetime", "julianday(\"CreatedAtUtc\") IS NOT NULL\nAND julianday(\"ExpiresAtUtc\") IS NOT NULL\nAND julianday(\"ExpiresAtUtc\") > julianday(\"CreatedAtUtc\")");

                            t.HasCheckConstraint("CK_SecurityCapabilities_Purpose", "\"Purpose\" IN ('BootstrapOwner', 'ActivateUser', 'RecoverOwner')");

                            t.HasCheckConstraint("CK_SecurityCapabilities_Revision", "Revision >= 0");

                            t.HasCheckConstraint("CK_SecurityCapabilities_RevocationTime", "\"RevokedAtUtc\" IS NULL\nOR (\n    julianday(\"RevokedAtUtc\") IS NOT NULL\n    AND julianday(\"RevokedAtUtc\") >= julianday(\"CreatedAtUtc\")\n)");

                            t.HasCheckConstraint("CK_SecurityCapabilities_TerminalState", "\"UsedAtUtc\" IS NULL OR \"RevokedAtUtc\" IS NULL");

                            t.HasCheckConstraint("CK_SecurityCapabilities_TokenHash_Length", "length(\"TokenHash\") = 32");

                            t.HasCheckConstraint("CK_SecurityCapabilities_UseTime", "\"UsedAtUtc\" IS NULL\nOR (\n    julianday(\"UsedAtUtc\") IS NOT NULL\n    AND julianday(\"UsedAtUtc\") >= julianday(\"CreatedAtUtc\")\n)");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Setup.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workspaces_Revision", "Revision >= 0");

                            t.HasCheckConstraint("CK_Workspaces_Singleton", "Id = 1");

                            t.HasCheckConstraint("CK_Workspaces_TimeZoneId_Length", "length(\"TimeZoneId\") BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_DisplayName_Length", "length(\"DisplayName\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_AspNetUsers_Email_Length", "\"Email\" IS NULL OR length(\"Email\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_NormalizedEmail_Length", "\"NormalizedEmail\" IS NULL OR length(\"NormalizedEmail\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_NormalizedUserName_Length", "\"NormalizedUserName\" IS NULL OR length(\"NormalizedUserName\") <= 256");

                            t.HasCheckConstraint("CK_AspNetUsers_UserName_Length", "\"UserName\" IS NULL OR length(\"UserName\") <= 256");
                        });
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Infrastructure.Persistence.ProtectedSecretRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProtectedSecrets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProtectedSecrets_Ciphertext", "length(\"Ciphertext\") > 0");

                            t.HasCheckConstraint("CK_ProtectedSecrets_Purpose", "length(\"Purpose\") BETWEEN 1 AND 128\nAND \"Purpose\" NOT GLOB '*[^A-Za-z0-9._:-]*'");

                            t.HasCheckConstraint("CK_ProtectedSecrets_Revision", "Revision >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Identity.Ownership", b =>
                {
                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TemperedTyrant.CreatorToolkit.Core.Identity.Ownership", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TemperedTyrant.CreatorToolkit.Core.Setup.Workspace", null)
                        .WithOne()
                        .HasForeignKey("TemperedTyrant.CreatorToolkit.Core.Identity.Ownership", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TemperedTyrant.CreatorToolkit.Core.Setup.SecurityCapability", b =>
                {
                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TemperedTyrant.CreatorToolkit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
